pipeline {
    agent any

    stages {
        stage('Build & Dockerize Car-Service') {
            steps {
                echo 'Building FastAPI application and creating Docker image...'
                sh 'docker build -t atakandockerdevops/arac_kiralama_fastapi1:latest -f car_service/Dockerfile car_service'
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing the Docker image to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                    sh 'docker push atakandockerdevops/arac_kiralama_fastapi1:latest'
                }
            }
        }
    }
}